# Generated by Django 4.2.6 on 2024-03-16 09:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RemainderDetails',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('date', models.DateField(null=True)),
                ('time', models.TimeField(blank=True)),
                ('remainder_type', models.CharField(choices=[('1', 'Sms'), ('2', 'Email')], max_length=1)),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
